### ISSUE TITLE
Item 10 on BOM - what is it?

### ISSUE THREAD

**Issue by Erroneous-Hyphen** [pmandes/C64-RF-Modulator#1]
Im not sure if this is just me not understanding - on the BOM item 11 is a ferrite bead, easy enough
Item 10 is an SMD component but is marked 'Ferrite Bead'.  Im not entirely sure what this is supposed to be - is it a line filter of some value? or an inductor?  my apologies if Im just failing to read the BOM correctly but I cant work it out for the life of me.

**Comment by pmandes** [comment]
Hi,

There are two options:

- you can use THT ferrite beads like in C64C (FB3, FB4):
i.e. [Murata-Electronics/BL02RN1R2M2B](https://www.mouser.pl/ProductDetail/Murata-Electronics/BL02RN1R2M2B?qs=rQrCv%2FN695EG0eyD3E3V4g%3D%3D)

**OR**

- use an equivalent SMD element with similar characteristics (impedance ~70Ω at 100MHz) (FB1, FB2)

They are used to filter out high-frequency disturbances and noise.
